# Generated by Django 5.1.1 on 2025-01-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_order_payment_completed_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa')], default='Cash on Delivery', max_length=20),
        ),
    ]
